Update stable-install

diff --git a/stable-install b/stable-install
--- a/stable-install
+++ b/stable-install
@@ -1,33 +1,81 @@
 #!/bin/sh
 set -e
 
-CHANNEL="stable"
+# This script is meant for quick & easy install via:
+#   $ curl -fsSL get.docker.com -o get-docker.sh
+#   $ sh get-docker.sh
+#
+# For test builds (ie. release candidates):
+#   $ curl -fsSL test.docker.com -o test-docker.sh
+#   $ sh test-docker.sh
+#
+# NOTE: Make sure to verify the contents of the script
+#       you downloaded matches the contents of install.sh
+#       located at https://github.com/docker/docker-install
+#       before executing.
+#
+# Git commit from https://github.com/docker/docker-install when
+# the script was uploaded (Should only be modified by upload job):
+SCRIPT_COMMIT_SHA=11aa13e
 
-docker_version=17.09.0
-apt_url="https://apt.dockerproject.org"
-yum_url="https://yum.dockerproject.org"
-gpg_fingerprint="9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
 
-key_servers="
-ha.pool.sks-keyservers.net
-pgp.mit.edu
-keyserver.ubuntu.com
-"
+# This value will automatically get changed for:
+#   * edge
+#   * test
+#   * experimental
+DEFAULT_CHANNEL_VALUE="stable"
+if [ -z "$CHANNEL" ]; then
+	CHANNEL=$DEFAULT_CHANNEL_VALUE
+fi
 
-rhel_repos="
-rhel-7-server-extras-rpms
-rhui-REGION-rhel-server-extras
-rhui-rhel-7-server-rhui-extras-rpms
+DOWNLOAD_URL="https://download.docker.com"
+
+SUPPORT_MAP="
+x86_64-centos-7
+x86_64-fedora-24
+x86_64-fedora-25
+x86_64-fedora-26
+x86_64-fedora-27
+x86_64-debian-wheezy
+x86_64-debian-jessie
+x86_64-debian-stretch
+x86_64-debian-buster
+x86_64-ubuntu-trusty
+x86_64-ubuntu-xenial
+x86_64-ubuntu-zesty
+x86_64-ubuntu-artful
+s390x-ubuntu-xenial
+s390x-ubuntu-zesty
+s390x-ubuntu-artful
+ppc64le-ubuntu-xenial
+ppc64le-ubuntu-zesty
+ppc64le-ubuntu-artful
+aarch64-ubuntu-xenial
+armv6l-raspbian-jessie
+armv7l-raspbian-jessie
+armv6l-raspbian-stretch
+armv7l-raspbian-stretch
+armv7l-debian-jessie
+armv7l-debian-stretch
+armv7l-debian-buster
+armv7l-ubuntu-trusty
+armv7l-ubuntu-xenial
+armv7l-ubuntu-zesty
+armv7l-ubuntu-artful
 "
 
 mirror=''
+DRY_RUN=${DRY_RUN:-}
 while [ $# -gt 0 ]; do
 	case "$1" in
 		--mirror)
 			mirror="$2"
 			shift
 			;;
-		*)
+		--dry-run)
+			DRY_RUN=1
+			;;
+		--*)
 			echo "Illegal option $1"
 			;;
 	esac
@@ -35,13 +83,11 @@ while [ $# -gt 0 ]; do
 done
 
 case "$mirror" in
-	AzureChinaCloud)
-		apt_url="https://mirror.azure.cn/docker-engine/apt"
-		yum_url="https://mirror.azure.cn/docker-engine/yum"
-		;;
 	Aliyun)
-		apt_url="https://mirrors.aliyun.com/docker-engine/apt"
-		yum_url="https://mirrors.aliyun.com/docker-engine/yum"
+		DOWNLOAD_URL="https://mirrors.aliyun.com/docker-ce"
+		;;
+	AzureChinaCloud)
+		DOWNLOAD_URL="https://mirror.azure.cn/docker-ce"
 		;;
 esac
 
@@ -49,7 +95,29 @@ command_exists() {
 	command -v "$@" > /dev/null 2>&1
 }
 
+is_dry_run() {
+	if [ -z "$DRY_RUN" ]; then
+		return 1
+	else
+		return 0
+	fi
+}
+
+get_distribution() {
+	lsb_dist=""
+	# Every system that we officially support has /etc/os-release
+	if [ -r /etc/os-release ]; then
+		lsb_dist="$(. /etc/os-release && echo "$ID")"
+	fi
+	# Returning an empty string here should be alright since the
+	# case statements don't act unless you provide an actual value
+	echo "$lsb_dist"
+}
+
 echo_docker_as_nonroot() {
+	if is_dry_run; then
+		return
+	fi
 	if command_exists docker && [ -e /var/run/docker.sock ]; then
 		(
 			set -x
@@ -59,22 +127,19 @@ echo_docker_as_nonroot() {
 	your_user=your-user
 	[ "$user" != 'root' ] && your_user="$user"
 	# intentionally mixed spaces and tabs here -- tabs are stripped by "<<-EOF", spaces are kept in the output
-	cat <<-EOF
+	echo "If you would like to use Docker as a non-root user, you should now consider"
+	echo "adding your user to the \"docker\" group with something like:"
+	echo
+	echo "  sudo usermod -aG docker $your_user"
+	echo
+	echo "Remember that you will have to log out and back in for this to take effect!"
+	echo
+	echo "WARNING: Adding a user to the \"docker\" group will grant the ability to run"
+	echo "         containers which can be used to obtain root privileges on the"
+	echo "         docker host."
+	echo "         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface"
+	echo "         for more information."
 
-	If you would like to use Docker as a non-root user, you should now consider
-	adding your user to the "docker" group with something like:
-
-	  sudo usermod -aG docker $your_user
-
-	Remember that you will have to log out and back in for this to take effect!
-
-	WARNING: Adding a user to the "docker" group will grant the ability to run
-	         containers which can be used to obtain root privileges on the
-	         docker host.
-	         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
-	         for more information.
-
-	EOF
 }
 
 # Check if this is a forked Linux distro
@@ -96,8 +161,8 @@ check_forked() {
 			EOF
 
 			# Get the upstream release info
-			lsb_dist=$(lsb_release -a -u 2>&1 | tr '[:upper:]' '[:lower:]' | grep -E 'id' | cut -d ':' -f 2 | tr -d '[[:space:]]')
-			dist_version=$(lsb_release -a -u 2>&1 | tr '[:upper:]' '[:lower:]' | grep -E 'codename' | cut -d ':' -f 2 | tr -d '[[:space:]]')
+			lsb_dist=$(lsb_release -a -u 2>&1 | tr '[:upper:]' '[:lower:]' | grep -E 'id' | cut -d ':' -f 2 | tr -d '[:space:]')
+			dist_version=$(lsb_release -a -u 2>&1 | tr '[:upper:]' '[:lower:]' | grep -E 'codename' | cut -d ':' -f 2 | tr -d '[:space:]')
 
 			# Print info about upstream distro
 			cat <<-EOF
@@ -107,7 +172,7 @@ check_forked() {
 			if [ -r /etc/debian_version ] && [ "$lsb_dist" != "ubuntu" ] && [ "$lsb_dist" != "raspbian" ]; then
 				# We're Debian and don't even know it!
 				lsb_dist=debian
-				dist_version="$(cat /etc/debian_version | sed 's/\/.*//' | sed 's/\..*//')"
+				dist_version="$(sed 's/\/.*//' /etc/debian_version | sed 's/\..*//')"
 				case "$dist_version" in
 					9)
 						dist_version="stretch"
@@ -132,59 +197,31 @@ semverParse() {
 	patch="${patch%%[-.]*}"
 }
 
-deprecation_notice() {
+ee_notice() {
 	echo
 	echo
-	echo "  WARNING: $1 is no longer updated @ $url"
-	echo "           Installing the legacy docker-engine package..."
+	echo "  WARNING: $1 is now only supported by Docker EE"
+	echo "           Check https://store.docker.com for information on Docker EE"
 	echo
 	echo
-	sleep 10;
 }
 
 do_install() {
-
-	architecture=$(uname -m)
-	case $architecture in
-		# officially supported
-		amd64|x86_64)
-			;;
-		# unofficially supported with available repositories
-		armv6l|armv7l)
-			;;
-		# unofficially supported without available repositories
-		aarch64|arm64|ppc64le|s390x)
-			cat 1>&2 <<-EOF
-			Error: This install script does not support $architecture, because no
-			$architecture package exists in Docker's repositories.
-
-			Other install options include checking your distribution's package repository
-			for a version of Docker, or building Docker from source.
-			EOF
-			exit 1
-			;;
-		# not supported
-		*)
-			cat >&2 <<-EOF
-			Error: $architecture is not a recognized platform.
-			EOF
-			exit 1
-			;;
-	esac
+	echo "# Executing docker install script, commit: $SCRIPT_COMMIT_SHA"
 
 	if command_exists docker; then
 		version="$(docker -v | cut -d ' ' -f3 | cut -d ',' -f1)"
 		MAJOR_W=1
 		MINOR_W=10
 
-		semverParse $version
+		semverParse "$version"
 
 		shouldWarn=0
-		if [ $major -lt $MAJOR_W ]; then
+		if [ "$major" -lt "$MAJOR_W" ]; then
 			shouldWarn=1
 		fi
 
-		if [ $major -le $MAJOR_W ] && [ $minor -lt $MINOR_W ]; then
+		if [ "$major" -le "$MAJOR_W" ] && [ "$minor" -lt "$MINOR_W" ]; then
 			shouldWarn=1
 		fi
 
@@ -236,60 +273,13 @@ do_install() {
 		fi
 	fi
 
-	curl=''
-	if command_exists curl; then
-		curl='curl -sSL'
-	elif command_exists wget; then
-		curl='wget -qO-'
-	elif command_exists busybox && busybox --list-modules | grep -q wget; then
-		curl='busybox wget -qO-'
-	fi
-
-	# check to see which repo they are trying to install from
-	if [ -z "$repo" ]; then
-		repo='main'
-		if [ "https://test.docker.com/" = "$url" ]; then
-			repo='testing'
-		elif [ "https://experimental.docker.com/" = "$url" ]; then
-			repo='experimental'
-		fi
+	if is_dry_run; then
+		sh_c="echo"
 	fi
 
 	# perform some very rudimentary platform detection
-	lsb_dist=''
-	dist_version=''
-	if command_exists lsb_release; then
-		lsb_dist="$(lsb_release -si)"
-	fi
-	if [ -z "$lsb_dist" ] && [ -r /etc/lsb-release ]; then
-		lsb_dist="$(. /etc/lsb-release && echo "$DISTRIB_ID")"
-	fi
-	if [ -z "$lsb_dist" ] && [ -r /etc/debian_version ]; then
-		lsb_dist='debian'
-	fi
-	if [ -z "$lsb_dist" ] && [ -r /etc/fedora-release ]; then
-		lsb_dist='fedora'
-	fi
-	if [ -z "$lsb_dist" ] && [ -r /etc/oracle-release ]; then
-		lsb_dist='oracleserver'
-	fi
-	if [ -z "$lsb_dist" ] && [ -r /etc/centos-release ]; then
-		lsb_dist='centos'
-	fi
-	if [ -z "$lsb_dist" ] && [ -r /etc/redhat-release ]; then
-		lsb_dist='redhat'
-	fi
-	if [ -z "$lsb_dist" ] && [ -r /etc/os-release ]; then
-		lsb_dist="$(. /etc/os-release && echo "$ID")"
-	fi
-
+	lsb_dist=$( get_distribution )
 	lsb_dist="$(echo "$lsb_dist" | tr '[:upper:]' '[:lower:]')"
-
-	# Special case redhatenterpriseserver
-	if [ "${lsb_dist}" = "redhatenterpriseserver" ]; then
-		# Set it to redhat, it will be changed to centos below anyways
-		lsb_dist='redhat'
-	fi
 
 	case "$lsb_dist" in
 
@@ -303,7 +293,7 @@ do_install() {
 		;;
 
 		debian|raspbian)
-			dist_version="$(cat /etc/debian_version | sed 's/\/.*//' | sed 's/\..*//')"
+			dist_version="$(sed 's/\/.*//' /etc/debian_version | sed 's/\..*//')"
 			case "$dist_version" in
 				9)
 					dist_version="stretch"
@@ -317,34 +307,48 @@ do_install() {
 			esac
 		;;
 
-		oracleserver)
-			# need to switch lsb_dist to match yum repo URL
-			lsb_dist="oraclelinux"
-			dist_version="$(rpm -q --whatprovides redhat-release --queryformat "%{VERSION}\n" | sed 's/\/.*//' | sed 's/\..*//' | sed 's/Server*//')"
+		centos)
+			if [ -z "$dist_version" ] && [ -r /etc/os-release ]; then
+				dist_version="$(. /etc/os-release && echo "$VERSION_ID")"
+			fi
 		;;
 
-		fedora|centos|redhat)
-			dist_version="$(rpm -q --whatprovides ${lsb_dist}-release --queryformat "%{VERSION}\n" | sed 's/\/.*//' | sed 's/\..*//' | sed 's/Server*//' | sort | tail -1)"
-		;;
+		rhel|ol|sles)
+			ee_notice "$lsb_dist"
+			exit 1
+			;;
 
 		*)
 			if command_exists lsb_release; then
-				dist_version="$(lsb_release --codename | cut -f2)"
+				dist_version="$(lsb_release --release | cut -f2)"
 			fi
 			if [ -z "$dist_version" ] && [ -r /etc/os-release ]; then
 				dist_version="$(. /etc/os-release && echo "$VERSION_ID")"
 			fi
 		;;
 
-
 	esac
 
 	# Check if this is a forked Linux distro
 	check_forked
 
+	# Check if we actually support this configuration
+	if ! echo "$SUPPORT_MAP" | grep "$(uname -m)-$lsb_dist-$dist_version" >/dev/null; then
+		cat >&2 <<-'EOF'
+
+		Either your platform is not easily detectable or is not supported by this
+		installer script.
+		Please visit the following URL for more detailed installation instructions:
+
+		https://docs.docker.com/engine/installation/
+
+		EOF
+		exit 1
+	fi
+
 	# Run setup for each distro accordingly
 	case "$lsb_dist" in
-		ubuntu|debian)
+		ubuntu|debian|raspbian)
 			pre_reqs="apt-transport-https ca-certificates curl"
 			if [ "$lsb_dist" = "debian" ] && [ "$dist_version" = "wheezy" ]; then
 				pre_reqs="$pre_reqs python-software-properties"
@@ -358,27 +362,36 @@ do_install() {
 			if ! command -v gpg > /dev/null; then
 				pre_reqs="$pre_reqs gnupg"
 			fi
-			apt_repo="deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/$lsb_dist $dist_version $CHANNEL"
+			apt_repo="deb [arch=$(dpkg --print-architecture)] $DOWNLOAD_URL/linux/$lsb_dist $dist_version $CHANNEL"
 			(
-				set -x
-				$sh_c 'apt-get update'
-				$sh_c "apt-get install -y -q $pre_reqs"
-				curl -fsSl "https://download.docker.com/linux/$lsb_dist/gpg" | $sh_c 'apt-key add -'
-				$sh_c "add-apt-repository \"$apt_repo\""
-				if [ "$lsb_dist" = "debian" ] && [ "$dist_version" = "wheezy" ]; then
-					$sh_c 'sed -i "/deb-src.*download\.docker/d" /etc/apt/sources.list'
+				if ! is_dry_run; then
+					set -x
 				fi
-				$sh_c 'apt-get update'
-				$sh_c "apt-get install -y -q docker-ce=$(apt-cache madison docker-ce | grep ${docker_version} | head -n 1 | cut -d ' ' -f 4)"
+				$sh_c 'apt-get update -qq >/dev/null'
+				$sh_c "apt-get install -y -qq $pre_reqs >/dev/null"
+				$sh_c "curl -fsSL \"$DOWNLOAD_URL/linux/$lsb_dist/gpg\" | apt-key add -qq - >/dev/null"
+				$sh_c "echo \"$apt_repo\" > /etc/apt/sources.list.d/docker.list"
+				if [ "$lsb_dist" = "debian" ] && [ "$dist_version" = "wheezy" ]; then
+					$sh_c 'sed -i "/deb-src.*download\.docker/d" /etc/apt/sources.list.d/docker.list'
+				fi
+				$sh_c 'apt-get update -qq >/dev/null'
+				$sh_c 'apt-get install -y -qq --no-install-recommends docker-ce >/dev/null'
 			)
 			echo_docker_as_nonroot
 			exit 0
 			;;
-		centos|fedora|redhat|oraclelinux)
-			yum_repo="https://download.docker.com/linux/centos/docker-ce.repo"
+		centos|fedora)
+			yum_repo="$DOWNLOAD_URL/linux/$lsb_dist/docker-ce.repo"
 			if [ "$lsb_dist" = "fedora" ]; then
+				if [ "$dist_version" = "24" ]; then
+					echo
+					echo "Warning: Fedora 24 has reached EOL"
+					echo "         Support for Fedora 24 for this installation script will be removed on October 1, 2017"
+					echo
+					sleep 10
+				fi
 				if [ "$dist_version" -lt "24" ]; then
-					echo "Error: Only Fedora >=24 are supported by $url"
+					echo "Error: Only Fedora >=24 are supported"
 					exit 1
 				fi
 				pkg_manager="dnf"
@@ -392,128 +405,39 @@ do_install() {
 				pre_reqs="yum-utils"
 			fi
 			(
-				set -x
-			        if [ "$lsb_dist" = "redhat" ]; then
-                                        for rhel_repo in $rhel_repos ; do
-                                                $sh_c "$config_manager $enable_channel_flag $rhel_repo"
-                                        done
-                                fi
+				if ! is_dry_run; then
+					set -x
+				fi
 				$sh_c "$pkg_manager install -y -q $pre_reqs"
 				$sh_c "$config_manager --add-repo $yum_repo"
+
+				# DELETE FROM HERE
+				if [ "$dist_version" -eq "27" ]; then
+					$sh_c "sed -i 's/\\\$releasever/26/g' /etc/yum.repos.d/docker-ce.repo"
+					set +x
+					echo "=================================================================================="
+					echo
+					echo "WARNING: Hardcoding repository to use Fedora 26 repositories"
+					echo "         You will need to update your repositories after the release of 17.12.0-ce"
+					echo
+					echo "         See: https://github.com/docker/for-linux/issues/164#issuecomment-345034887"
+					echo
+					echo "=================================================================================="
+					sleep 10
+					set -x
+				fi
+				# DELETE TO HERE
+
 				if [ "$CHANNEL" != "stable" ]; then
-					echo "Info: Enabling channel '$CHANNEL' for docker-ce repo"
 					$sh_c "$config_manager $enable_channel_flag docker-ce-$CHANNEL"
 				fi
-				$sh_c "$pkg_manager makecache fast"
-				$sh_c "$pkg_manager install -y -q docker-ce-${docker_version}.ce"
-				if [ -d '/run/systemd/system' ]; then
-					$sh_c 'service docker start'
-				else
-					$sh_c 'systemctl start docker'
-				fi
+				$sh_c "$pkg_manager makecache"
+				$sh_c "$pkg_manager install -y -q docker-ce"
 			)
 			echo_docker_as_nonroot
-			exit 0
-			;;
-		raspbian)
-			deprecation_notice "$lsb_dist"
-			export DEBIAN_FRONTEND=noninteractive
-
-			did_apt_get_update=
-			apt_get_update() {
-				if [ -z "$did_apt_get_update" ]; then
-					( set -x; $sh_c 'sleep 3; apt-get update' )
-					did_apt_get_update=1
-				fi
-			}
-
-			if [ "$lsb_dist" != "raspbian" ]; then
-				# aufs is preferred over devicemapper; try to ensure the driver is available.
-				if ! grep -q aufs /proc/filesystems && ! $sh_c 'modprobe aufs'; then
-					if uname -r | grep -q -- '-generic' && dpkg -l 'linux-image-*-generic' | grep -qE '^ii|^hi' 2>/dev/null; then
-						kern_extras="linux-image-extra-$(uname -r) linux-image-extra-virtual"
-
-						apt_get_update
-						( set -x; $sh_c 'sleep 3; apt-get install -y -q '"$kern_extras" ) || true
-
-						if ! grep -q aufs /proc/filesystems && ! $sh_c 'modprobe aufs'; then
-							echo >&2 'Warning: tried to install '"$kern_extras"' (for AUFS)'
-							echo >&2 ' but we still have no AUFS.  Docker may not work. Proceeding anyways!'
-							( set -x; sleep 10 )
-						fi
-					else
-						echo >&2 'Warning: current kernel is not supported by the linux-image-extra-virtual'
-						echo >&2 ' package.  We have no AUFS support.  Consider installing the packages'
-						echo >&2 ' "linux-image-virtual" and "linux-image-extra-virtual" for AUFS support.'
-						( set -x; sleep 10 )
-					fi
-				fi
-			fi
-
-			# install apparmor utils if they're missing and apparmor is enabled in the kernel
-			# otherwise Docker will fail to start
-			if [ "$(cat /sys/module/apparmor/parameters/enabled 2>/dev/null)" = 'Y' ]; then
-				if command -v apparmor_parser >/dev/null 2>&1; then
-					echo 'apparmor is enabled in the kernel and apparmor utils were already installed'
-				else
-					echo 'apparmor is enabled in the kernel, but apparmor_parser is missing. Trying to install it..'
-					apt_get_update
-					( set -x; $sh_c 'sleep 3; apt-get install -y -q apparmor' )
-				fi
-			fi
-
-			if [ ! -e /usr/lib/apt/methods/https ]; then
-				apt_get_update
-				( set -x; $sh_c 'sleep 3; apt-get install -y -q apt-transport-https ca-certificates' )
-			fi
-			if [ -z "$curl" ]; then
-				apt_get_update
-				( set -x; $sh_c 'sleep 3; apt-get install -y -q curl ca-certificates' )
-				curl='curl -sSL'
-			fi
-			if ! command -v gpg > /dev/null; then
-				apt_get_update
-				( set -x; $sh_c 'sleep 3; apt-get install -y -q gnupg2 || apt-get install -y -q gnupg' )
-			fi
-
-			# dirmngr is a separate package in ubuntu yakkety; see https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1634464
-			if ! command -v dirmngr > /dev/null; then
-				apt_get_update
-				( set -x; $sh_c 'sleep 3; apt-get install -y -q dirmngr' )
-			fi
-
-			(
-			set -x
-                        for key_server in $key_servers ; do
-                                $sh_c "apt-key adv --keyserver hkp://${key_server}:80 --recv-keys ${gpg_fingerprint}" && break
-                        done
-                        $sh_c "apt-key adv -k ${gpg_fingerprint} >/dev/null"
-			$sh_c "mkdir -p /etc/apt/sources.list.d"
-			$sh_c "echo deb \[arch=$(dpkg --print-architecture)\] ${apt_url}/repo ${lsb_dist}-${dist_version} ${repo} > /etc/apt/sources.list.d/docker.list"
-			$sh_c 'sleep 3; apt-get update; apt-get install -y -q docker-engine'
-			)
-			echo_docker_as_nonroot
-			exit 0
-			;;
-		rancheros)
-			(
-			set -x
-			$sh_c "sleep 3; ros engine switch -f $(sudo ros engine list | grep ${docker_version} | head -n 1 | cut -d ' ' -f 2)"
-			)
 			exit 0
 			;;
 	esac
-
-	# intentionally mixed spaces and tabs here -- tabs are stripped by "<<-'EOF'", spaces are kept in the output
-	cat >&2 <<-'EOF'
-
-	Either your platform is not easily detectable or is not supported by this
-	installer script.
-	Please visit the following URL for more detailed installation instructions:
-
-	https://docs.docker.com/engine/installation/
-
-	EOF
 	exit 1
 }
 
